pipeline {
    agent any

    stages {
        stage('Setup') {
            steps {
                dir('lab2') {
                    sh '''
                        python3 -m venv venv
                        venv/bin/pip install --upgrade pip
                        venv/bin/pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Data Creation') {
            steps {
                dir('lab2') {
                    sh 'venv/bin/python data_creation.py'
                }
            }
        }

        stage('Data Preprocessing') {
            steps {
                dir('lab2') {
                    sh 'venv/bin/python data_preprocessing.py'
                }
            }
        }

        stage('Model Preparation') {
            steps {
                dir('lab2') {
                    sh 'venv/bin/python model_preparation.py'
                }
            }
        }

        stage('Model Testing') {
            steps {
                dir('lab2') {
                    sh 'venv/bin/python model_testing.py'
                }
            }
        }
    }

    post {
        always {
            dir('lab2') {
                echo 'Pipeline finished in lab2'
                // При необходимости можно добавить очистку:
                // sh 'rm -rf venv'
            }
        }
    }
}